config/routes.rb
Rails.application.routes.draw do

  root 'artists#index'

  resources :punchlines
  resources :artists do
    resources :punchlines
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/models/song.rb
# A song is a title and the lyrics associated
# An artist is linked to the song

# Song
#   title: string
#   lyrics: text
#   artist_id: integer
class Song < ActiveRecord::Base
  belongs_to :artist

  def random_line_num
    rand(lyrics_array.length - 1)
  end

  def find_lyrics(line_num)
    [lyrics_array[line_num], lyrics_array[line_num + 1]]
  end

  private

  def lyrics_array
    @_lyrics_array = lyrics.split("\n").reject do |e|
      e.blank? || e.length < 3
    end
  end
end

app/controllers/application_controller.rb
# Application Controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
# Artists controller
class ArtistsController < ApplicationController
  def index
    redirect_to [Artist.first, :punchlines]
  end
end

app/controllers/punchlines_controller.rb
# Controller of the /punchlines route
class PunchlinesController < ApplicationController
  def index
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.order('RANDOM()').first
    @random_line_num = @song.random_line_num
    @random_lines = @song.try(:find_lyrics, @random_line_num)
    @title = @song.try(:title)
    @artist = @song.try(:artist)
  end

  def show
    if (@song = Song.find_by_id(params[:id].split('-').first))
      @random_line_num = params[:id].split('-').last.to_i
      @random_lines = @song.try(:find_lyrics, @random_line_num)
      @title = @song.try(:title)
      @artist = @song.try(:artist)
    else
      render :song_not_found
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlkPunchlines</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body class="<%= @artist.slug %>">

  <%= yield %>

</body>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-69140448-1', 'auto');
  ga('send', 'pageview');
</script>

</html>

app/views/punchlines/index.html.slim
br
.content
  h2= @artist.name
  .title
    h3= @title
  .lyrics
    br
    = @random_lines[0]
    br
    = @random_lines[1]

  .link
    = 'Partager cette punchline :'
    br
    = link_to root_url.to_s[0..-2] + artist_punchline_path(@artist, "#{@song.id}-#{@random_line_num}"), artist_punchline_path(@artist, "#{@song.id}-#{@random_line_num}")
    br
    br
    .social
      a href='https://twitter.com/share' class='twitter-share-button' data-url='#{artist_punchline_path(@artist, "#{@song.id}-#{@random_line_num}")}' data-text='#{@random_lines[0] + "\n" + @random_lines[1] + "\n" + root_url.to_s[0..-2] +artist_punchline_path(@artist, "#{@song.id}-#{@random_line_num}")}' data-count='horizontal' data-via='alkpunchlines'
        = 'Tweet'
      script type='text/javascript' src='https://platform.twitter.com/widgets.js'

  .next onclick='location.reload();'
    = 'NEXT'

app/views/punchlines/show.html.slim
br
.content
  h2= @artist.name
  .title
    h3= @title
  .lyrics
    br
    = @random_lines[0]
    br
    = @random_lines[1]



  .link
    = 'Partager cette punchline :'
    br
    = link_to root_url.to_s[0..-2] + artist_punchline_path(@artist, "#{@song.id}-#{@random_line_num}"), artist_punchline_path(@artist, "#{@song.id}-#{@random_line_num}")
    br
    br

    .social
      a href='https://twitter.com/share' class='twitter-share-button' data-url='#{artist_punchline_path(@artist, "#{@song.id}-#{@random_line_num}")}' data-text='#{@random_lines[0] + "\n" + @random_lines[1] + "\n" + root_url.to_s[0..-2] +artist_punchline_path(@artist, "#{@song.id}-#{@random_line_num}")}' data-count='horizontal' data-via='alkpunchlines'
        = 'Tweet'
      script type='text/javascript' src='https://platform.twitter.com/widgets.js'


  .next onclick="location = '/artists/#{@artist.slug}/punchlines';"
    = 'NEXT'

app/views/punchlines/song_not_found.html.slim
br
.content
  .title
    | CETTE PUNCHLINE N'EXISTE PAS